import datetime
import xml.etree.ElementTree as ET

def generate_epg():
    # 根っことなる XMLTV のルート要素を作成
    tv = ET.Element("tv")
    
    # チャンネル情報の定義（Rally.TV用）
    channel = ET.SubElement(tv, "channel", id="rally.tv")
    display_name = ET.SubElement(channel, "display-name")
    display_name.text = "Rally.TV"
    
    # 本日の日付を基準にしたサンプル・番組データの生成
    # （※実際のAPIやサイト構造に合わせてURLやスクレイピング処理を拡張できます）
    now = datetime.datetime.utcnow()
    start_time = now.strftime("%Y%m%d%H%M00 +0000")
    stop_time = (now + datetime.timedelta(hours=6)).strftime("%Y%m%d%H%M00 +0000")
    
    programme = ET.SubElement(tv, "programme", start=start_time, stop=stop_time, channel="rally.tv")
    
    title = ET.SubElement(programme, "title", lang="en")
    title.text = "Rally.TV Live & Highlights"
    
    desc = ET.SubElement(programme, "desc", lang="en")
    desc.text = "Automated EPG data generated by your dedicated GitHub Actions robot with Ai."

    # XMLツリーをファイル（epg.xml）として書き出し
    tree = ET.ElementTree(tv)
    ET.indent(tree, space="  ", level=0)
    tree.write("epg.xml", encoding="utf-8", xml_declaration=True)
    print("EPG XML generated successfully!")

if __name__ == "__main__":
    generate_epg()
